"""initial_schema

Revision ID: 612cf3b25d9d
Revises: 
Create Date: 2026-05-20 06:31:05.218626

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '612cf3b25d9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lab_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('asset_tag', sa.String(length=100), nullable=True),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'under_calibration', 'under_maintenance', 'out_of_service', 'retired', name='equipmentstatus'), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('last_calibration_date', sa.Date(), nullable=True),
    sa.Column('next_calibration_date', sa.Date(), nullable=True),
    sa.Column('calibration_interval_days', sa.Integer(), nullable=True),
    sa.Column('calibration_cert_path', sa.String(length=500), nullable=True),
    sa.Column('comm_protocol', sa.String(length=50), nullable=True),
    sa.Column('comm_port', sa.String(length=100), nullable=True),
    sa.Column('comm_baud_rate', sa.Integer(), nullable=True),
    sa.Column('comm_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id')
    )
    op.create_table('report_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_path', sa.String(length=500), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('lab_name', sa.String(length=500), nullable=True),
    sa.Column('accreditation_number', sa.String(length=100), nullable=True),
    sa.Column('lab_address', sa.Text(), nullable=True),
    sa.Column('lab_phone', sa.String(length=50), nullable=True),
    sa.Column('lab_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'supervisor', 'analyst', 'viewer', 'client', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lab_section', sa.String(length=100), nullable=True),
    sa.Column('signature_image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analytical_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_es', sa.String(length=255), nullable=False),
    sa.Column('reference_standard', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('instrument_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('draft', 'under_review', 'approved', 'obsolete', name='methodstatus'), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['method_versions.id'], name='fk_method_current_version', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytical_methods_code'), 'analytical_methods', ['code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'login', 'logout', 'approve', 'reject', 'print', 'transfer', 'upload', 'download', name='auditaction'), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('calibration_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('calibration_date', sa.Date(), nullable=False),
    sa.Column('calibration_type', sa.String(length=50), nullable=False),
    sa.Column('performed_by_id', sa.UUID(), nullable=False),
    sa.Column('external_provider', sa.String(length=255), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('certificate_path', sa.String(length=500), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('measurements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.Enum('sop', 'method', 'work_instruction', 'quality_manual', 'form', 'policy', 'certificate', 'external_standard', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'under_review', 'approved', 'obsolete', 'withdrawn', name='documentstatus'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('review_interval_months', sa.Integer(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['document_versions.id'], name='fk_document_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_number'), 'documents', ['doc_number'], unique=True)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('performed_by_id', sa.UUID(), nullable=True),
    sa.Column('external_technician', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('downtime_hours', sa.Float(), nullable=True),
    sa.Column('parts_replaced', sa.Text(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_quality_grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_es', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('regulatory_reference', sa.String(length=255), nullable=True),
    sa.Column('is_regulatory', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('training_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('training_title', sa.String(length=255), nullable=False),
    sa.Column('training_date', sa.Date(), nullable=False),
    sa.Column('trainer', sa.String(length=255), nullable=False),
    sa.Column('evidence_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('method_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_es', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('lod', sa.Float(), nullable=True),
    sa.Column('loq', sa.Float(), nullable=True),
    sa.Column('uncertainty_percent', sa.Float(), nullable=True),
    sa.Column('uncertainty_coverage_factor', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['analytical_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('authored_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authored_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('method_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('method_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('content_path', sa.String(length=500), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('authored_by_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['authored_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['analytical_methods.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lab_code', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('client_reference', sa.String(length=100), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('matrix', sa.Enum('extra_virgin_olive_oil', 'virgin_olive_oil', 'refined_olive_oil', 'olive_pomace_oil', 'blend', 'other', name='samplematrix'), nullable=False),
    sa.Column('declared_grade_id', sa.UUID(), nullable=True),
    sa.Column('sample_description', sa.Text(), nullable=True),
    sa.Column('origin_country', sa.String(length=100), nullable=True),
    sa.Column('harvest_year', sa.Integer(), nullable=True),
    sa.Column('producer', sa.String(length=255), nullable=True),
    sa.Column('quantity_received_ml', sa.Float(), nullable=True),
    sa.Column('container_type', sa.String(length=100), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('received', 'in_preparation', 'in_analysis', 'qc_review', 'supervisor_review', 'approved', 'reported', 'archived', 'rejected', name='samplestatus'), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('storage_temperature', sa.Float(), nullable=True),
    sa.Column('received_by_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['declared_grade_id'], ['product_quality_grades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index(op.f('ix_samples_lab_code'), 'samples', ['lab_code'], unique=True)
    op.create_table('user_qualifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('method_id', sa.UUID(), nullable=False),
    sa.Column('qualified_by_id', sa.UUID(), nullable=False),
    sa.Column('qualification_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('certificate_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['method_id'], ['analytical_methods.id'], ),
    sa.ForeignKeyConstraint(['qualified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyte_specifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analyte_id', sa.UUID(), nullable=False),
    sa.Column('quality_grade_id', sa.UUID(), nullable=False),
    sa.Column('min_limit', sa.Float(), nullable=True),
    sa.Column('max_limit', sa.Float(), nullable=True),
    sa.Column('limit_note', sa.String(length=500), nullable=True),
    sa.Column('uncertainty_override', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analyte_id'], ['analytes.id'], ),
    sa.ForeignKeyConstraint(['quality_grade_id'], ['product_quality_grades.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.String(length=50), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates_of_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coa_number', sa.String(length=50), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('issued_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('overall_compliance', sa.String(length=100), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_hash', sa.String(length=64), nullable=True),
    sa.Column('client_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_of_analysis_coa_number'), 'certificates_of_analysis', ['coa_number'], unique=True)
    op.create_table('control_charts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('method_id', sa.UUID(), nullable=False),
    sa.Column('analyte_id', sa.UUID(), nullable=False),
    sa.Column('qc_type', sa.Enum('blank', 'method_blank', 'calibration_standard', 'control_standard', 'duplicate', 'spike', 'proficiency_sample', name='qctype'), nullable=False),
    sa.Column('established_from', sa.Date(), nullable=False),
    sa.Column('established_to', sa.Date(), nullable=False),
    sa.Column('n_points', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('sd', sa.Float(), nullable=False),
    sa.Column('ucl', sa.Float(), nullable=False),
    sa.Column('lcl', sa.Float(), nullable=False),
    sa.Column('uwl', sa.Float(), nullable=False),
    sa.Column('lwl', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analyte_id'], ['analytes.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['analytical_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qc_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_code', sa.String(length=50), nullable=False),
    sa.Column('method_id', sa.UUID(), nullable=False),
    sa.Column('analyte_id', sa.UUID(), nullable=False),
    sa.Column('qc_type', sa.Enum('blank', 'method_blank', 'calibration_standard', 'control_standard', 'duplicate', 'spike', 'proficiency_sample', name='qctype'), nullable=False),
    sa.Column('analyst_id', sa.UUID(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['analyte_id'], ['analytes.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['analytical_methods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_code')
    )
    op.create_table('sample_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_custody',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=True),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('method_id', sa.UUID(), nullable=False),
    sa.Column('method_version_id', sa.UUID(), nullable=True),
    sa.Column('assigned_analyst_id', sa.UUID(), nullable=True),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'results_entered', 'qc_check', 'supervisor_review', 'approved', 'failed_qc', 'retest_required', name='teststatus'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_analyst_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['method_id'], ['analytical_methods.id'], ),
    sa.ForeignKeyConstraint(['method_version_id'], ['method_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gc_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_request_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('import_format', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_by_id', sa.UUID(), nullable=False),
    sa.Column('peaks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_request_id'], ['test_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qc_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qc_batch_id', sa.UUID(), nullable=False),
    sa.Column('analyte_id', sa.UUID(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('measured_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('percent_recovery', sa.Float(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['analyte_id'], ['analytes.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qc_batch_id'], ['qc_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_instrument_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('test_request_id', sa.UUID(), nullable=True),
    sa.Column('reading_type', sa.String(length=50), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['test_request_id'], ['test_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_request_id', sa.UUID(), nullable=False),
    sa.Column('analyte_id', sa.UUID(), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=True),
    sa.Column('reported_value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('is_below_lod', sa.Boolean(), nullable=False),
    sa.Column('is_below_loq', sa.Boolean(), nullable=False),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('in_spec', sa.Boolean(), nullable=True),
    sa.Column('compliance_note', sa.Text(), nullable=True),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('raw_instrument_reading_id', sa.UUID(), nullable=True),
    sa.Column('entered_by_id', sa.UUID(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replicate_number', sa.Integer(), nullable=False),
    sa.Column('dilution_factor', sa.Float(), nullable=True),
    sa.Column('sample_weight_g', sa.Float(), nullable=True),
    sa.Column('volume_ml', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['analyte_id'], ['analytes.id'], ),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_instrument_reading_id'], ['raw_instrument_readings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_request_id'], ['test_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('westgard_violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qc_result_id', sa.UUID(), nullable=False),
    sa.Column('rule_violated', sa.Enum('rule_1_2s', 'rule_1_3s', 'rule_2_2s', 'rule_r_4s', 'rule_4_1s', 'rule_10x', name='westgardrule'), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('investigated_by_id', sa.UUID(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qc_result_id'], ['qc_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('westgard_violations')
    op.drop_table('test_results')
    op.drop_table('raw_instrument_readings')
    op.drop_table('qc_results')
    op.drop_table('gc_imports')
    op.drop_table('test_requests')
    op.drop_table('sample_custody')
    op.drop_table('sample_attachments')
    op.drop_table('qc_batches')
    op.drop_table('control_charts')
    op.drop_index(op.f('ix_certificates_of_analysis_coa_number'), table_name='certificates_of_analysis')
    op.drop_table('certificates_of_analysis')
    op.drop_table('approval_records')
    op.drop_table('analyte_specifications')
    op.drop_table('user_qualifications')
    op.drop_index(op.f('ix_samples_lab_code'), table_name='samples')
    op.drop_table('samples')
    op.drop_table('method_versions')
    op.drop_table('document_versions')
    op.drop_table('analytes')
    op.drop_table('training_records')
    op.drop_table('product_quality_grades')
    op.drop_table('maintenance_logs')
    op.drop_index(op.f('ix_documents_doc_number'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('calibration_records')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analytical_methods_code'), table_name='analytical_methods')
    op.drop_table('analytical_methods')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('report_templates')
    op.drop_table('equipment')
    # ### end Alembic commands ###
